baseurl = "https://fcblingbling.fi"
DefaultContentLanguage = "fi"
title = "FC Bling Bling"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "FC Bling Bling on tamperelainen naisten futisjoukkue. Höntsäämme hyvällä meiningillä."
  mainSections = ["post"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "2.1.2006"
  commit = false
  rss = false
  comments = false
  readingTime = false
  wordCount = false
  useHLJS = false
  socialShare = false
  delayDisqus = false
  showRelatedPosts = false
  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "FC Bling Bling ry"
#  website = "fcblingbling.fi"
  email = "fcblingbling@gmail.com"
  facebook = "fcblingbling"
#  github = "username"
#  gitlab = "username"
#  bitbucket = "username"
#  twitter = "username"
#  reddit = "username"
#  linkedin = "username"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
  instagram = "fcblingbling"
#  youtube = "user/username" # or channel/channelname
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  vk = "username"
#  paypal = "username"
#  telegram = "username"
#  500px = "username"
#  codepen = "username"
#  mastodon = "url"
#  kaggle = "username"
#  weibo = "username"
#  slack = "username"
#  discord = "invite code (https://discord.gg/XXXXXXX)"
#  strava = "userid"

[[menu.main]]
    name = "Uutiset"
    url = "feed"
    weight = 1

[[menu.main]]
    name = "Säännöt"
    url = "rules"
    weight = 2

[[menu.main]]
    name = "Kuntopallo"
    url = "series"
    weight = 3

[[menu.main]]
    name = "Futsal"
    url = "futsal"
    weight = 4

#[[menu.main]]
#    identifier = "samples"
#    name = "Samples"
#    weight = 2

#[[menu.main]]
#    parent = "samples"
#    name = "Big Image Sample"
#    url = "post/2017-03-07-bigimg-sample"
#    weight = 1

#[[menu.main]]
#    parent = "samples"
#    name = "Math Sample"
#    url = "post/2017-03-05-math-sample"
#    weight = 2

#[[menu.main]]
#    parent = "samples"
#    name = "Code Sample"
#    url = "post/2016-03-08-code-sample"
#    weight = 3

#[[menu.main]]
#    name = "Tags"
#    url = "tags"
#    weight = 3
